### ISSUE TITLE
simpleCollections without pgOmitListSuffix: true will throw error

### ISSUE THREAD

**Issue by andreechristian** [graphile/postgraphile#1008]
I'm submitting a ... 

* [x] bug report
* [ ] feature request
* [ ] question 

PostGraphile version:

4.2.0

Minimal SQL file that can be loaded into a clean database:

```sql
CREATE TABLE "user" (
 id serial PRIMARY KEY
);

CREATE TABLE photo (
 id serial PRIMARY KEY,
 url TEXT
);

CREATE TABLE user_photo (
 user_id integer references "user"(id),
 photo_id integer references "photo"(id),
 PRIMARY KEY (user_id, photo_id)
);
```

Steps to reproduce:

Current behavior:
Use `PgSimplifyInflectorPlugin` in conjunction with `simpleCollections: 'only' || 'both'` **without** `graphileBuildOptions: { pgOmitListSuffix: true }` will throw error:
`Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "userPhotos-list" does not.`
Expected behavior:
It shouldn't throw error.

**Comment by benjie** [comment]
This should be an issue against https://github.com/graphile-contrib/pg-simplify-inflector; also it should already be fixed in the latest version? If it isn't, please re-raise against that repo and note the version number you're using 👍

**Comment by andreechristian** [comment]
@benjie I wasn't aware that this is https://github.com/graphile-contrib/pg-simplify-inflector bug because i read about `simpleCollections` on https://www.graphile.org/postgraphile/v4-new-features/. Also, i tested it on 4.3.3 and it still happening. I will move this issue to pg-simplify-inflector bug.
Thank you for your super fast response :)
